stages:
  - lint
  - package
  - publish


lint-chart:
  stage: lint
  image: alpine/k8s:1.16.15
  script:
    - helm dependency update
    - helm lint

package:
  stage: package
  image: alpine/k8s:1.16.15
  script:
    - helm dependency update
    - 'curl https://storage.googleapis.com/$CHART_REPO_BUCKET_NAME/index.yaml --output ./index.yaml --fail || :'
    - helm package .
    - helm repo index --merge ./index.yaml .
  artifacts:
    untracked: true
    paths:
      - index.yaml

publish-chart:
  stage: publish
  image: google/cloud-sdk
  dependencies:
    - package
  script:
      - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
      - gsutil cp ./index.yaml gs://$CHART_REPO_BUCKET_NAME 
      - gsutil cp *.tgz gs://$CHART_REPO_BUCKET_NAME

