stages:
  - lint
  - package
  - publish


lint-chart:
  stage: lint
  image: alpine/k8s:1.16.15
  script:
    - helm dependency update
    - helm lint

publish-chart:
  stage: publish
  image: alpine/k8s:1.16.15
  script:
      - helm plugin install https://github.com/chartmuseum/helm-push.git
      - helm repo add spherics https://charts.spherics.space
      - helm push . spherics 

