---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "diaspora.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "diaspora.name" . }}
    helm.sh/chart: {{ include "diaspora.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  diaspora.yml: |
    configuration:
      environment: 
        {{- if .Values.diaspora.configuration.environment.url }}
        url: {{ .Values.diaspora.configuration.environment.url }}
        {{- else }}
        url: {{ include "diaspora.hostURL" . }}
        {{ end}}

        certificate_authorities: '/etc/ssl/certs/ca-certificates.crt'

        {{- if .Values.diaspora.configuration.environment.redis }}
        redis: {{ .Values.diaspora.configuration.environment.redis }}
        {{- else }}
        redis: {{ include "diaspora.redisUrl" . }}
        {{ end}}

        require_ssl: {{ .Values.diaspora.configuration.environment.require_ssl }}

        single_process_mode: {{ .Values.diaspora.configuration.environment.single_process_mode }}

        ## Sidekiq - background processing
        sidekiq:
{{- toYaml .Values.diaspora.configuration.environment.sidekiq | nindent 10 }}

        s3:
{{- toYaml .Values.diaspora.configuration.environment.s3 | nindent 10 }}

        assets:
{{- toYaml .Values.diaspora.configuration.environment.assets | nindent 10 }}

        #pubsub_server: {{ .Values.diaspora.configuration.environment.pubsub_server }}

        ## Logger configuration
        logging:
{{- toYaml .Values.diaspora.configuration.environment.logging | nindent 10 }}

      ## Settings affecting how ./script/server behaves.
      server: 
        listen: {{ printf "0.0.0.0:%g" .Values.service.port }}

        pid: 'tmp/pids/web.pid'

        rails_environment: {{ .Values.diaspora.configuration.server.rails_environment }}

        # stderr_log: {{ .Values.diaspora.configuration.server.stderr_log }}
        # stdout_log: {{ .Values.diaspora.configuration.server.stdout_log }}

        unicorn_worker: {{ .Values.diaspora.configuration.server.unicorn_worker }}

        unicorn_timeout: {{ .Values.diaspora.configuration.server.unicorn_timeout }}

        embed_sidekiq_worker: {{ .Values.diaspora.configuration.server.embed_sidekiq_worker }}

        sidekiq_workers: {{ .Values.diaspora.configuration.server.sidekiq_workers }}

      chat:
{{- toYaml .Values.diaspora.configuration.chat | nindent 8 }}

      map:
{{- toYaml .Values.diaspora.configuration.map | nindent 8 }}

      privacy:
{{- toYaml .Values.diaspora.configuration.privacy | nindent 8 }}

      settings:
{{- toYaml .Values.diaspora.configuration.settings | nindent 8 }}

      services:
{{- toYaml .Values.diaspora.configuration.services | nindent 8 }}

      mail:
{{- toYaml .Values.diaspora.configuration.mail | nindent 8 }}

      admins:
{{- toYaml .Values.diaspora.configuration.admins | nindent 8 }}

    production:
{{- toYaml .Values.diaspora.production | nindent 6 }}
    development:
{{- toYaml .Values.diaspora.development | nindent 6 }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "diaspora.fullname" . }}-database
  labels:
    app.kubernetes.io/name: {{ include "diaspora.name" . }}
    helm.sh/chart: {{ include "diaspora.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  database.yml: |
    postgresql: &postgresql
      adapter: postgresql
      host: {{ (include "postgresql.host" .) }}
      port: {{ .Values.postgresql.global.postgresql.servicePort }}
      username: {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
      password: {{ .Values.postgresql.global.postgresql.postgresqlPassword | quote }}
      encoding: unicode

    # Comment the postgresql line and uncomment the mysql line
    # if you want to use mysql
    common: &common
      {{ if .Values.database.postgresql.enabled }}
      <<: *postgresql
      {{ end }}

      # Should match environment.sidekiq.concurrency
      #pool: 25

    ##################################################
    #### CONFIGURE ABOVE #############################
    ##################################################

    # Normally you don't need to touch anything here

    combined: &combined
      <<: *common
    development:
      <<: *combined
      database: diaspora_development
    production:
      <<: *combined
      database: diaspora_production
    test:
      <<: *combined
      database: "diaspora_test"
    integration1:
      <<: *combined
      database: diaspora_integration1
    integration2:
      <<: *combined
      database: diaspora_integration2
