apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diaspora.fullname" . }}
  labels:
    {{- include "diaspora.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diaspora.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "diaspora.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "diaspora.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- if .Values.diaspora.database.mysql.enabled }}
      initContainers:
      - name: mysql-isalive
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        env:
        - name: MYSQL_USER
          value: {{ .Values.mysql.db.user | quote }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.db.password | quote }}
        command:
          - "sh"
          - "-c"
          - {{ printf "until mysql --host=%s-mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute=\"SELECT 1;\"; do echo waiting for mysql; sleep 2; done;" .Release.Name }}
      {{- else if .Values.diaspora.database.postgresql.enabled }}
      initContainers:
      - name: postgresql-isready
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        env:
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.global.postgresql.postgresqlUsername | quote }}
        command:
          - "sh"
          - "-c"
          - {{ printf "until pg_isready -h %s-postgresql -U ${POSTGRES_USER} ; do sleep 2 ; done" .Release.Name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/home/diaspora/diaspora/config/diaspora.yml"
              readOnly: true
              subPath: "diaspora.yml"
            - name: database
              mountPath: "/home/diaspora/diaspora/config/database.yml"
              readOnly: true
              subPath: "database.yml"
          livenessProbe:
            httpGet:
              path: /statistics
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /statistics
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ template "diaspora.fullname" . }}-config
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "diaspora.yml"
                path: "diaspora.yml"
        - name: database
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: {{ template "diaspora.fullname" . }}-database
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "database.yml"
                path: "database.yml"
